// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using endsem_project.Models;

#nullable disable

namespace endsem_project.Migrations
{
    [DbContext(typeof(TodoDBContext))]
    [Migration("20240421140440_migrations1")]
    partial class migrations1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("endsem_project.Models.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Priority")
                        .HasColumnType("longtext")
                        .HasColumnName("Priority");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Task");

                    b.Property<string>("TaskTag")
                        .HasColumnType("longtext")
                        .HasColumnName("Tags");

                    b.HasKey("Id");

                    b.ToTable("Todo");
                });
#pragma warning restore 612, 618
        }
    }
}
